apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: expressapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expressapp
  template:
    metadata:
      labels:
        app: expressapp
    spec:
      containers:
      - name: expressapp
        image: deedeo/expressapp
        ports:
        - containerPort: 3000
